name = "PlutoPublish"
uuid = "8101fb26-ae3c-408d-aed3-f7cb81499a91"
authors = ["Connor Burns <cburns@cot.llc>"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.17.7"
julia = "1.6"
